### ISSUE TITLE
Add tool for handling single release file for py2, py3, rhel6 rhel7 builds

### ISSUE THREAD

**Issue by ManInFez** [equinor/komodo#116]
The new release file use the folling format: 
```
# non py specific
lib-something: 1.0
# non rhel specific
lib:
  py2: 1.0
  py3: 1.0+py3
# rhel specific
otherlib:
  rhel6:
    py2: 1.0
    py3: 1.0+py3
  rhel7:
    py2: 0.9
    py3: 0.9+py3
```

The new format should be then transpiled into release files to be built.
