### ISSUE TITLE
Format of repository yaml file too verbose

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/komodo#27]
The format of the repository file is unnecessarily verbose. In most cases, different versions of the same software use exactly the same settings. As a user, I would appreciate to be able to add a new version of a software without having to duplicate the entire configuration

**Comment by pgdr** [comment]
We already "support" this by simply using anchors and refs.

In this example, `argcomplete→1.10.0` has exactly the same content as `argcomplete→1.9.5`.

We need to be careful, though, to never change the anchor once one version has been deployed as that would make it difficult to go back and rebuild old versions exactly.

(Of course, it's all version controlled, so it would of course be possible.)

```yaml
argcomplete_default: &argcomplete_def
  source: pypi
  make: pip
  maintainer: pgdr
  depends:
  - setuptools
  - python

argcomplete:
  1.10.0:
    *argcomplete_def
  1.9.5:
    source: pypi
    make: pip
    maintainer: pgdr
    depends:
      - setuptools
      - python
```
