### ISSUE TITLE
Make the transpiler arguments agnostic

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/komodo#310]
Currently the transpiler has hardcoded both keys (i.e. python-version and rhel) and values (3.8 and 7 respectively), the latter will be added as a command line option in https://github.com/equinor/komodo/issues/308. However, the setup should really be agnostic of the keys.

E.g, one could consider the following specification in this valid release file:

```
a: 0.0.1
b:
  rhel-7: 0.0.1
  rhel-8: 0.0.2
c:
  py-2:
    rhel-7: 0.0.1
    rhel-8: 0.0.2
  py-3: 0.0.3
```

Currently it is valid because the `py` and `rhel` prefix is hardcoded. But it is possible to determine these keys by looking at the file itself. Hence it should be possible to have the `transpiler` unaware of the names of the keys.

The arguments entered when using the transpiler could be for instance `rhel: 7 py: [2,3]` (click sort of supports key,val. Have not looked into it a lot..).
