### ISSUE TITLE
matrix files expected format too permissive?

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/komodo#358]
at the moment our tests seem to allow for all sorts of inputs in a matrix release file - adding the following block to `tests/data/test_release_matrix.yml` passes all tests:

```yaml
lib5:
  py38: 2.2.2
  py27: 3.4.5
  py310: 2.2.2
  rhel4:
    py38: 2.2.2
    py66: 23.2.2
  py44:
    rhel2: 23.2.2
    py310: 4.0.0
```

which is at least to me a bit funny and unexpected.

perhaps we need more tests, perhaps we should be more opinioniated about input validation of matrix files.
