### ISSUE TITLE
komodo-clean-repository cleanup removes packages in use

### ISSUE THREAD

**Issue by andreas-el** [equinor/komodo#476]
Running the following yields unwanted removal:

```
komodo-clean-repository cleanup --repository repository.yml --releases releases/matrices/* --output repo-changed.yml
```

Excerpt from bleeding.yml:

```
opm:
  py38: '2022.4' # fmu-sumo-sim2sumo requires opm<=2022.4, webviz-subsurface 0.2.19 has requirement opm<=2022.10
  py311: '2023.10' # Only the newest version of opm has wheels for py311
...
...
python:
  rhel7:
    py38: 3.8.6-builtin
  rhel8:
    py38: 3.8-builtin+rhel8
    py311: 3.11-builtin

```

These packages was proposed removed:

```diff
@@ -12168,13 +12154,6 @@
       - numpy

 opm:
-  '2023.10':
-    source: pypi
-    make: pip
-    maintainer: scout
-    depends:
-      - python
-      - setuptools
   '2022.4':
     source: pypi
     make: pip
@@ -14004,16 +13983,6 @@
     makefile: build__python-virtualenv.sh
     maintainer: scout
     makeopts: --virtualenv-interpreter /opt/rh/rh-python38/root/usr/bin/python3.8
-  3.8-builtin+rhel8:
-    make: sh
-    makefile: build__python-virtualenv.sh
-    maintainer: scout
-    makeopts: --virtualenv-interpreter /usr/bin/python3.8
-  3.11-builtin:
-    make: sh
-    makefile: build__python-virtualenv.sh
-    maintainer: scout
-    makeopts: --virtualenv-interpreter /usr/bin/python3.11
```
