### ISSUE TITLE
Make it possible to specify extras in the package status file

### ISSUE THREAD

**Issue by eivindjahren** [equinor/komodo#518]
We would like to specify that `ert` with the extra specifier `everest` is a public package.

In order to do so, we would like to be able to specify that extra in the `package_status`:

```
ert:
  visibility: public
  maturity: stable
  importance: high
  extras: everest
```
