### ISSUE TITLE
Automatically extend the release file when no expanding coordinates

### ISSUE THREAD

**Issue by andreas-el** [equinor/komodo#526]
Given that the PR https://github.com/equinor/komodo/pull/525 is merged in, komodo will have the capability to have `rhel`, `py` and a custom coordinate for transpiling releases.

This would be a valid release file that could be transpiled using the following command:
```
komodo-transpiler transpile --matrix-file <file>  --output-folder tmp --matrix-coordinates "{rhel: ['8', '9'], py: ['3.8', '3.11'], numpy: ['1', '2']}"
```

```
parcel:
  numpy1: 1.0.0
  numpy2: 2.0.0
letter:
  py38:
    numpy1: 1.38.0
    numpy2: 2.28.0
  py311:
    numpy1: 1.311.0
    numpy2: 2.211.0
box:
  rhel8:
    py38:
      numpy1: 1.38.8
      numpy2: 2.28.8
    py311:
      numpy1: 1.311.8
      numpy2: 2.211.8
  rhel9:
    py38:
      numpy1: 1.38.9
      numpy2: 2.28.9
    py311:
      numpy1: 1.311.9
      numpy2: 2.211.9
case: 0.0.1
```

So there is a certain ruleset in place, one of these needs to be met:
1. Only package number
2. Custom coordinate and package
3. Python coordinate and custom coordinate
4. Rhel coordinate and python coordinate and custom coordinate

If the release with no custom coordinates in release file or command line string, same rules but no custom coordinate requirement.

What if we could extend transpiling with the capability to automatically fill in the missing coordinates?

```
$ cat aa.yml 
lib1:
  rhel8:
    py38: 1.2.4
    py311: 1.2.5
```

Would be interpreted as:

```
$ cat aa.yml 
lib1:
  rhel8:
    py38:
       numpy1: 1.2.4
       numpy2: 1.2.4
    py311:
       numpy1: 1.2.5
       numpy2: 1.2.5
```

There are some situations where this might be beneficial:
- No custom coordinate specified in release file (example), but rhel & py coordinate was
- Only rhel coordinate specified in release file
- Only python coordinate specified in release file (but custom coordinate was transpiled for)
